'use client';

import { useRouter } from 'next/navigation';

export default function MarketingHomepage() {
  const router = useRouter();

  return (
    <div className="relative min-h-[90vh] overflow-hidden bg-[#f5f5f7] dark:bg-[#000000] transition-colors duration-300">

      {/* Aurora Breathing Ambient Glow */}
      <div className="absolute top-1/4 left-1/2 -translate-x-1/2 w-[500px] h-[500px] bg-cyan-500/10 dark:bg-blue-600/15 rounded-full blur-[120px] animate-pulse duration-[8000ms]"></div>
      <div className="absolute bottom-10 left-10 w-[300px] h-[300px] bg-sky-500/5 dark:bg-cyan-600/10 rounded-full blur-[100px] animate-pulse duration-[6000ms]"></div>

      {/* Hero Section */}
      <section className="relative z-10 max-w-5xl mx-auto px-6 pt-20 pb-16 text-center space-y-8">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/60 dark:bg-neutral-900/60 border border-white/40 dark:border-neutral-800/40 backdrop-blur-md shadow-sm">
          <span className="w-1.5 h-1.5 rounded-full bg-cyan-500 animate-pulse"></span>
          <span className="text-[10px] font-bold tracking-wider uppercase text-neutral-500 dark:text-neutral-400">Version 2.0 Dynamic Engine</span>
        </div>

        <h1 className="text-4xl sm:text-6xl font-extrabold tracking-tight text-neutral-900 dark:text-white leading-tight max-w-3xl mx-auto">
          Your cold email pipeline.{' '}
          <span className="bg-gradient-to-r from-cyan-600 to-blue-600 dark:from-cyan-400 dark:to-blue-400 bg-clip-text text-transparent">
            On autopilot.
          </span>
        </h1>

        <p className="text-base sm:text-lg text-neutral-550 dark:text-neutral-400 max-w-2xl mx-auto leading-relaxed">
          Connect Gmail and Notion. Wake up to personalized cold email drafts for 30+ companies generated by Claude. Review, approve, and send in minutes.
        </p>

        <div className="flex flex-col sm:flex-row justify-center items-center gap-4">
          <button
            onClick={() => router.push('/login')}
            className="w-full sm:w-auto px-8 h-13 rounded-2xl bg-black text-white dark:bg-white dark:text-black font-semibold text-sm hover:scale-102 transition-all duration-200 shadow-md shadow-cyan-500/10 cursor-pointer"
          >
            Get Started Free
          </button>
          <a
            href="https://utkarshkr13.notion.site/Job-Outreach-Tracker-154df656a87747e98d9ee812a1f9e812"
            target="_blank"
            rel="noreferrer"
            className="w-full sm:w-auto px-8 h-13 rounded-2xl border border-neutral-300 dark:border-neutral-800 hover:bg-neutral-100 dark:hover:bg-neutral-900/60 text-neutral-750 dark:text-neutral-300 font-semibold text-sm transition-all duration-200 flex items-center justify-center gap-2 cursor-pointer"
          >
            Notion Template
          </a>
        </div>
      </section>

      {/* How it Works */}
      <section className="relative z-10 max-w-5xl mx-auto px-6 py-16 border-t border-[#e8e8ed]/60 dark:border-neutral-900/60">
        <h2 className="text-2xl font-bold tracking-tight text-neutral-900 dark:text-white text-center mb-12">How it works</h2>
        <div className="grid md:grid-cols-3 gap-8">
          {[
            { n: '1', title: 'Add leads in Notion', desc: 'Paste target company data and contact emails into your job tracker Notion CRM database using our template.' },
            { n: '2', title: 'Claude creates drafts', desc: 'Every morning, our AI engine digests your resume, profile bio, and target company to write highly personalized cold drafts.' },
            { n: '3', title: 'Approve and send', desc: 'Open your dashboard, read the generated drafts, and dispatch them directly from your Gmail with a single click.' },
          ].map(({ n, title, desc }) => (
            <div key={n} className="p-6 rounded-2xl backdrop-blur-md bg-white/40 dark:bg-neutral-900/40 border border-white/50 dark:border-neutral-850/50 shadow-sm space-y-4">
              <div className="w-10 h-10 rounded-xl bg-violet-50 dark:bg-violet-950/20 text-cyan-600 dark:text-cyan-400 flex items-center justify-center text-lg font-bold">{n}</div>
              <h3 className="font-semibold text-sm text-neutral-900 dark:text-white">{title}</h3>
              <p className="text-xs text-neutral-500 dark:text-neutral-450 leading-relaxed">{desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Features Grid */}
      <section className="relative z-10 max-w-5xl mx-auto px-6 py-16 border-t border-[#e8e8ed]/60 dark:border-neutral-900/60">
        <h2 className="text-2xl font-bold tracking-tight text-neutral-900 dark:text-white text-center mb-12">Core Features</h2>
        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {[
            { title: 'Gmail Integration', desc: 'Emails originate and deliver directly from your personal Gmail address.', icon: '✉️' },
            { title: 'Resume Auto-Annex', desc: 'Upload your resume PDF and let the system append it as an attachment.', icon: '📄' },
            { title: 'Approve, Reject, Redo', desc: 'Complete manual control. Edit subjects, reject poor matches, or request AI revisions.', icon: '⚙️' },
            { title: 'Notion as your CRM', desc: 'Maintain full control of your job search pipeline. No learning curve.', icon: '📓' },
            { title: 'Secure Multi-Tenancy', desc: 'All credentials are encrypted using AES-256-CBC.', icon: '🔒' },
            { title: 'Local Dev Sandbox', desc: 'Fully offline capable development mode with no API keys needed.', icon: '📦' },
          ].map((f, i) => (
            <div key={i} className="p-6 rounded-2xl bg-white/45 dark:bg-neutral-900/25 border border-neutral-200/50 dark:border-neutral-850/50 space-y-2">
              <span className="text-xl block mb-2">{f.icon}</span>
              <h4 className="font-semibold text-xs text-neutral-900 dark:text-white">{f.title}</h4>
              <p className="text-[11px] text-neutral-500 dark:text-neutral-450 leading-relaxed">{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Final CTA */}
      <section className="relative z-10 max-w-5xl mx-auto px-6 py-16 text-center space-y-6">
        <h2 className="text-2xl font-bold text-neutral-900 dark:text-white">Take control of your outreach today</h2>
        <p className="text-xs text-neutral-500 dark:text-neutral-450 max-w-md mx-auto">
          Sign up now, duplicate the Notion template, and start sending highly personalized cold emails in minutes.
        </p>
        <button
          onClick={() => router.push('/login')}
          className="px-8 h-12 rounded-xl bg-black text-white dark:bg-white dark:text-black font-semibold text-sm hover:scale-102 transition-all cursor-pointer shadow-md"
        >
          Start for Free
        </button>
        <div className="text-[10px] text-neutral-400 mt-2">No credit card required. Free tier includes up to 20 monthly cold drafts.</div>
      </section>
    </div>
  );
}
